# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LSMetricsSample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LSMetricsSample
  pod 'LSMetrics',:path =>'../'

  target 'LSMetricsSampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LSMetricsSampleUITests' do
    # Pods for testing
  end

end
